version: '3.8'
services:
    mongodb:
        image: 'mongo'
        container_name: insta-mongo
        environment:
            - MONGO_INITDB_DATABASE=test
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        ports:
            - 27017:27017
        networks:
            - instantw
    backend:
        build: ./server
        environment:
            - DB_URI=mongodb://admin:admin@mongodb:27017/?retryWrites=true&w=majority
        ports:
            - 3001:3001
        depends_on:
            - mongodb
        networks:
            - instantw
    frontend:
        build: ./client
        ports:
            - 3000:3000
        stdin_open: true
        tty: true
        depends_on:
            - backend
networks:
    instantw:
        driver: bridge
